### PR TITLE
Support for Block Matrices

### PR DESCRIPTION
**Pull request by Ulfgard**
I have added operators | and & to be able to create block matrices easier. e.g. adding a columns of all ones at the end is as easy as (X|1).

and a matrix
A B
C D

is created by (A |B) & (C | D)

### CODE REVIEW

**Comment by TGlas** [comment]
Let's stick to the example block matrix

```
    A B
    C D
```

which is created by the expression `(A | B) & (C | D)`.
The brackets are necessary because `operator &` has a
higher precedence (binds stronger) than `operator |`.
How about swapping the roles of the operators so that
we can write the same expression without brackets:
`A & B | C & D`. This has the added benefit of resembling
LaTeX notations (with `|` instead of `\\`). In code this
could be nicely formetted as follows:

```
    auto M = A & B |
             C & D ;
```

Of course, with
the current syntax we could do `A & C | B & D`, but
personally I find that more confusing.

**Comment by Ulfgard** [comment]
Omg, someone reads those!

I can very well understand your latex argument, that also came to my mind. 
I can understand that argument. My argument is that it is more common in the literature to use | for separation of matrix blocks and therefore the usual case should be (A|B) or (A|1) or... 

See the updated example of linear regression using (X|1) throughout the whole thing. would you rather see that as (X & 1)? (I personally see all other uses as "rare academic cases")

**Comment by TGlas** [comment]
Also fine :)

**Comment by Ulfgard** [comment]
don't understand your comment :)

**Comment by TGlas** [comment]
I mean: forget about my previous comment, I see your point. Leave it as is.

**Pull request merged**
